# Graficos
FPS = 240
FACTOR_DIAGONAL = 1
ESPACIO_RELATIVO = 64

# Mapa
ALTO = 50
ANCHO = 100
SEMILLA = 666
ALTO_BASE = ALTO * ESPACIO_RELATIVO
ANCHO_BASE = ANCHO * ESPACIO_RELATIVO

# Jugador
RETRAZO_MOVIMIENTO_JUGADOR = 60
# NPC
RETRAZO_MOVIMIENTO_NPC = 120
RETRAZO_CAMBIO_RUTA_NPC = 200
